PANDOC ?= pandoc

# Reproducible build from 2021-03-05
SOURCE_DATE_EPOCH := 1614902400
export SOURCE_DATE_EPOCH

all: sstic2021_ghidra_arcompact.pdf sstic2021_tpm_ssh.pdf

sstic2021_ghidra_arcompact.pdf: sstic_author-template/AnalyzingARCompactFirmwareWithGhidra.pdf
	cp -f $< $@

sstic2021_tpm_ssh.pdf: sstic_author-template/ProtectingSshAuthenticationWithTpm20.pdf
	cp -f $< $@

sstic_author-template/%.pdf: sstic_author-template/%/master.tex sstic_author-template/%/biblio.bib sstic_author-template/sstic.cls
	$(MAKE) -C sstic_author-template from_podman

# Remove some sequences generated by pandoc and insert non-breakable spaces where appropriate
sstic_author-template/%/master.tex: sstic_author-template/%/master.tex.tmp
	sed \
		-e 's:\\passthrough{\\lstinline!\([^!]\+\)!}:\\texttt{\1}:g' \
		-e 's:^\\tightlist$$::g' \
		-e 's:\(\S\)\\cite:\1~\\cite:g' \
		-e 's:\(\S\)\\ref:\1~\\ref:g' \
		< $< > $@

sstic_author-template/AnalyzingARCompactFirmwareWithGhidra/master.tex.tmp: sstic2021_ghidra_arcompact.md Makefile
	$(PANDOC) -f markdown-auto_identifiers -t latex+raw_tex --number-sections --listings -o $@ $<

sstic_author-template/ProtectingSshAuthenticationWithTpm20/master.tex.tmp: sstic2021_tpm_ssh.md Makefile
	$(PANDOC) -f markdown-auto_identifiers -t latex+raw_tex --number-sections --listings -o $@ $<

# To build a standalone document (to test things):
# (cd sstic_author-template && pandoc --pdf-engine=xelatex -t pdf --number-sections --bibliography AnalyzingARCompactFirmwareWithGhidra/biblio.bib -o sstic2021_ghidra_arcompact.pdf ../sstic2021_ghidra_arcompact.md)
# (cd sstic_author-template && pandoc --pdf-engine=xelatex -t pdf --number-sections --bibliography ProtectingSshAuthenticationWithTpm20/biblio.bib -o sstic2021_tpm_ssh.pdf ../sstic2021_tpm_ssh.md)

clean:
	$(RM) sstic2021_ghidra_arcompact.pdf sstic2021_tpm_ssh.pdf ./*.tmp sstic_author-template/*/master.tex.tmp
	$(MAKE) -C sstic_author-template clean

.PHONY: all clean
